"""SUPPLY_DRYING_UP semantic-quality audit.

Freezes the production-emission population generated by the candidate audit and
verifies the exact production semantic requirements at each emitted target bar.
No production configuration is mutated.
"""
from __future__ import annotations

import os
import sys

import pandas as pd

ROOT = os.path.abspath(os.path.join(os.path.dirname(__file__), ".."))
if ROOT not in sys.path:
    sys.path.insert(0, ROOT)

from data import daily_to_weekly, download_data
from engine.columns import COL_DIRECTION, COL_SPREAD_CLASS, COL_VOLUME_CLASS
from evidence.engine import EvidenceEngine
from metrics_engine import MetricsEngine
from models import Direction, EvidenceCode, SpreadClass, VolumeClass
from trend import TrendAnalyzer

SYMBOLS = (
    "BHARTIARTL.NS",
    "HDFCBANK.NS",
    "ICICIBANK.NS",
    "INFY.NS",
    "LT.NS",
    "RELIANCE.NS",
    "SBIN.NS",
    "TCS.NS",
)

TARGET_CODE = EvidenceCode.SUPPLY_DRYING_UP
EXPECTED_CANDIDATES = 547
EXPECTED_EVENTS = 225


def cheap_candidate(metrics: pd.DataFrame, index: int) -> bool:
    row = metrics.iloc[index]
    return (
        Direction(int(row[COL_DIRECTION])) == Direction.DOWN
        and VolumeClass(int(row[COL_VOLUME_CLASS])) <= VolumeClass.LOW
        and SpreadClass(int(row[COL_SPREAD_CLASS])) <= SpreadClass.BELOW_AVERAGE
    )


def main() -> None:
    cheap_total = 0
    emitted_total = 0
    duplicates = 0
    mandatory_failures = 0
    counts = {
        "down_bar": 0,
        "low_volume": 0,
        "narrow_spread": 0,
    }
    failures: list[dict[str, str]] = []
    context_rebuilds = 0

    for symbol in SYMBOLS:
        try:
            metrics = MetricsEngine().calculate(
                daily_to_weekly(download_data(symbol))
            )

            indices = [
                i
                for i in range(1, len(metrics) - 8)
                if cheap_candidate(metrics, i)
            ]
            cheap_total += len(indices)

            for index in indices:
                replay = metrics.iloc[: index + 1].copy()
                trend = TrendAnalyzer().analyze(replay)
                context_rebuilds += 1

                result = EvidenceEngine().collect(
                    metrics=replay,
                    trend=trend,
                    structural_swings=tuple(trend.structure.structural_swings),
                )

                targets = [
                    item
                    for item in result.evidence
                    if item.code is TARGET_CODE and item.bar_index == index
                ]

                if len(targets) > 1:
                    duplicates += len(targets) - 1
                    continue
                if not targets:
                    continue

                emitted_total += 1
                row = metrics.iloc[index]

                down = Direction(int(row[COL_DIRECTION])) == Direction.DOWN
                low_volume = VolumeClass(int(row[COL_VOLUME_CLASS])) <= VolumeClass.LOW
                narrow = SpreadClass(int(row[COL_SPREAD_CLASS])) <= SpreadClass.NARROW

                counts["down_bar"] += int(down)
                counts["low_volume"] += int(low_volume)
                counts["narrow_spread"] += int(narrow)

                mandatory_failures += int(not (down and low_volume and narrow))

        except Exception as exc:
            failures.append({"symbol": symbol, "error": str(exc)})

    failures_out = list(failures)

    if cheap_total != EXPECTED_CANDIDATES:
        failures_out.append({
            "scope": "candidate_population",
            "error": f"expected {EXPECTED_CANDIDATES}, got {cheap_total}",
        })

    if emitted_total != EXPECTED_EVENTS:
        failures_out.append({
            "scope": "production_emissions",
            "error": f"expected {EXPECTED_EVENTS}, got {emitted_total}",
        })

    if duplicates:
        failures_out.append({
            "scope": "duplicates",
            "error": f"duplicate emissions: {duplicates}",
        })

    if mandatory_failures:
        failures_out.append({
            "scope": "semantics",
            "error": f"mandatory semantic failures: {mandatory_failures}",
        })

    print("SUPPLY_DRYING_UP SEMANTIC-QUALITY AUDIT")
    print({
        "symbols_requested": len(SYMBOLS),
        "symbols_with_results": len(SYMBOLS) - len(failures),
        "cheap_candidates": cheap_total,
        "production_emissions": emitted_total,
        "expected_events": EXPECTED_EVENTS,
        "semantic_counts": counts,
        "mandatory_semantic_failures": mandatory_failures,
        "duplicate_emissions": duplicates,
        "heavy_context_rebuilds": context_rebuilds,
        "target_bar_only": True,
        "point_in_time": True,
        "production_context_used": True,
        "production_emission_authority": True,
        "confirmations_are_non_mandatory": True,
        "failures": failures_out,
        "status": "FAIL" if failures_out else "PASS",
    })


if __name__ == "__main__":
    main()
